<?php

/**
 * CondicionCargosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CondicionCargosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CondicionCargosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CondicionCargos');
    }
}