<?php

/**
 * DireccionesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DireccionesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DireccionesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Direcciones');
    }
}