<?php

/**
 * MediosLaboralesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MediosLaboralesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MediosLaboralesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MediosLaborales');
    }
}