<?php

/**
 * NivelesAcademicosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelesAcademicosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelesAcademicosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NivelesAcademicos');
    }
}