<?php

/**
 * SubsistemasLaboralesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubsistemasLaboralesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubsistemasLaboralesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubsistemasLaborales');
    }
}