<?php

/**
 * TiposPersonalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiposPersonalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiposPersonalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TiposPersonal');
    }
}