<?php

/**
 * TipoVoluntariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoVoluntariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoVoluntariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoVoluntarios');
    }
}