<?php

/**
 * VoluntariosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class VoluntariosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object VoluntariosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Voluntarios');
    }
}